### ISSUE TITLE
配置文件使用lua的io读取，影响性能

### ISSUE THREAD

**Issue by horan-geeker** [loveshell/ngx_lua_waf#128]
lua的io是阻塞的，直接使用io.open来读取wafconf下的配置文件，在访问量较大的业务场景，每个请求都会产生io消耗，过多的请求会阻塞，推荐wafconf下的配置文件使用lua的table来写，nginx加载进lua文件后会缓存到内存，不会进行io级别的调用

**Comment by horan-geeker** [comment]
后来发现一个简单的办法来解决io问题，就是在文件全局的位置写一个变量来读取配置，`local file = io.open('config')` 这样是一次加载

**Comment by ryan668** [comment]
这个项目好像不维护了

**Comment by smsjs** [comment]
> 后来发现一个简单的办法来解决io问题，就是在文件全局的位置写一个变量来读取配置，`local file = io.open('config')` 这样是一次加载

请教下怎么写呢

**Comment by horan-geeker** [comment]
lua 加载文件时会缓存整个文件内容，比如说你不写函数直接写文件里写上：
```
local file = io.open('config')
```
那 openresty 重启 nginx 执行一次这行代码，之后的请求不会再加载

**Comment by horan-geeker** [comment]
> > 后来发现一个简单的办法来解决io问题，就是在文件全局的位置写一个变量来读取配置，`local file = io.open('config')` 这样是一次加载
> 
> 请教下怎么写呢



> > 后来发现一个简单的办法来解决io问题，就是在文件全局的位置写一个变量来读取配置，`local file = io.open('config')` 这样是一次加载
> 
> 请教下怎么写呢

lua 加载文件时会缓存整个文件内容，比如说你不写函数直接写文件里写上：
```
local file = io.open('config')
```
那 openresty 重启 nginx 执行一次这行代码，之后的请求不会再加载

**Comment by horan-geeker** [comment]
> > > > 后来发现一个简单的办法来解决io问题，就是在文件全局的位置写一个变量来读取配置，`local file = io.open('config')` 这样是一次加载
> > > 
> > > 
> > > 请教下怎么写呢
> > 
> > 
> > lua 加载文件时会缓存整个文件内容，比如说你不写函数直接写文件里写上：
> > ```
> > local file = io.open('config')
> > ```
> > 那 openresty 重启 nginx 执行一次这行代码，之后的请求不会再加载
> 
> 根据代码，规则的设置应该是在init_by_lua阶段读取并用来注册判定函数的，这个阶段根据nginx_lua模块的解析应该是只有在master加载设置文件的时候运行，而且是在全局lua虚拟环境(global Lua VM)下运行的，应该只会打开设置文件一次把。

嗯，你说到点子上了，是我没仔细看，我把 issue 关了去，愧对作者 😢
