### ISSUE TITLE
wordpress 古腾堡编辑器更新文章 被拦截

### ISSUE THREAD

**Issue by wierli** [loveshell/ngx_lua_waf#158]
![未命名1614331528](https://user-images.githubusercontent.com/10514236/109281863-cb1b8b80-7857-11eb-8ca6-fa2cf2d05280.png)
![未命名1614331522](https://user-images.githubusercontent.com/10514236/109281876-cce54f00-7857-11eb-8d60-19aeda3aa154.png)
![未命名1614331514](https://user-images.githubusercontent.com/10514236/109281879-cd7de580-7857-11eb-846e-a51bc246e1a5.png)
如何解决呢？

**Comment by Aoocodee** [comment]
添加白名单
