### ISSUE TITLE
由于同时大量请求连接做校验出现503错误怎么处理？

### ISSUE THREAD

**Issue by zhangfulv** [loveshell/ngx_lua_waf#159]
在nginx.conf屏蔽掉这个校验配置就不会报错.

**Comment by ADD-SP** [comment]
估计是短时间请求次数太多被识别为 CC 攻击了。

可以的话可以试试我的防火墙模块，还在更新，我也会尽快回复 issue。https://github.com/ADD-SP/ngx_waf

这个项目已经四年不更新了，我厚着脸皮来这里贴一下我的项目应该可以吧（

**Comment by zhangfulv** [comment]
> 估计是短时间请求次数太多被识别为 CC 攻击了。
> 
> 可以的话可以试试我的防火墙模块，还在更新，我也会尽快回复 issue。https://github.com/ADD-SP/ngx_waf
> 
> 这个项目已经四年不更新了，我厚着脸皮来这里贴一下我的项目应该可以吧（

是的，昨晚我也是看见这个配置了，修改了之后发现问题应该是解决了。谢谢

**Comment by ADD-SP** [comment]
既然解决了就关掉 issue 吧，作者很久没有 Github 上的活动了，不能指望作者来关了。

**Comment by zhangfulv** [comment]
> 既然解决了就关掉 issue 吧，作者很久没有 Github 上的活动了，不能指望作者来关了。

好的。感谢回复.
