### ISSUE TITLE
上传文件post请求被拦截

### ISSUE THREAD

**Issue by innger** [loveshell/ngx_lua_waf#35]
上传图片时候，图片内容log打印出来是乱码，匹配的规则显示：rule=\.\./ 
有的图片是正常的，有些图片被拦截，这是bug么？

**Comment by loveshell** [comment]
https://github.com/loveshell/ngx_lua_waf/blob/master/wafconf/post
在这里修改下规则就行了。
比如您这个问题，只需要删掉../这条规则即可
