### ISSUE TITLE
README 文件和现有程序有些差异啊,能不能更新一下

### ISSUE THREAD

**Issue by etangyushan** [loveshell/ngx_lua_waf#36]
因为README中提到的gloab的规则等文件已经不存在了，所以感觉有些困惑。 
global留着挺好的啊，为什就删除了？
还有一个问题就是get怎么删除了，只留了一个post规则啊？

**Comment by loveshell** [comment]
args规则里的配置会对get和post都生效的
url的规则配置也会对url生效。所以去掉了get配置
global的文件为啥删了我一时也没想起来了。
