### ISSUE TITLE
master分支 init.lua报错

### ISSUE THREAD

**Issue by icanfly** [loveshell/ngx_lua_waf#39]
你好，我下载了你的master分支，使用的是openresty，配置好后，根据你提供的测试地址，直接报错，麻烦看下什么问题？

2015/04/01 11:12:22 [error] 13860#0: *1 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/waf/init.lua:130: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'pairs'
        /usr/local/openresty/nginx/conf/waf/init.lua:130: in function 'ua'
        /usr/local/openresty/nginx/conf/waf/waf.lua:11: in function </usr/local/openresty/nginx/conf/waf/waf.lua:1>, client: 192.168.1.108, server: 192.*, request: "GET /test.php?id=../etc/passwd HTTP/1.1", host: "192.168.1.35:6110"

**Comment by loveshell** [comment]
配置config.lua里的waf规则目录(一般在waf/conf/目录下)

    RulePath = "/usr/local/nginx/conf/waf/wafconf/"
绝对路径如有变动，需对应修改

**Comment by icanfly** [comment]
这个我配置了的。。。但是还是报错的

**Comment by ZhanHui-Xu** [comment]
thks，it works for me.
