### ISSUE TITLE
似乎fileExtCheck(ext)会过滤通过flash的上传

### ISSUE THREAD

**Issue by ladygh** [loveshell/ngx_lua_waf#40]
如题，启用后会拦截部分正常的文件上传请求（discuz的flash批量上传），但是同样的图片，有的时候拦截有的时候又不拦截，很是奇怪，但是基本拦截的全是JPG的

123.150.107.24 [2015-04-17 17:07:05] "POST /misc.php?mod=swfupload&action=swfupload&operation=upload&fid=201" "-"  "Shockwave Flash" "file attack with ext JPG"
123.150.107.30 [2015-04-17 17:07:13] "POST /misc.php?mod=swfupload&action=swfupload&operation=upload&fid=201" "-"  "Shockwave Flash" "file attack with ext JPG"
123.150.107.24 [2015-04-17 17:07:37] "POST /misc.php?mod=swfupload&action=swfupload&operation=upload&fid=201" "-"  "Shockwave Flash" "file attack with ext JPG"
123.150.107.26 [2015-04-17 17:07:44] "POST /misc.php?mod=swfupload&action=swfupload&operation=upload&fid=201" "-"  "Shockwave Flash" "file attack with ext JPG"
123.150.107.29 [2015-04-17 17:07:49] "POST /misc.php?mod=swfupload&action=swfupload&operation=upload&fid=201" "-"  "Shockwave Flash" "file attack with ext JPG"
123.150.107.25 [2015-04-17 17:08:00] "POST /misc.php?mod=swfupload&action=swfupload&operation=upload&fid=201" "-"  "Shockwave Flash" "file attack with ext JPG"
123.150.107.29 [2015-04-17 17:08:05] "POST /misc.php?mod=swfupload&action=swfupload&operation=upload&fid=201" "-"  "Shockwave Flash" "file attack with ext JPG"

**Comment by ladygh** [comment]
另外一个问题就是启用waf后会引起discuz的门户编辑功能失效，下面这个动作会返回500错误
原因不明。。
17/Apr/2015:17:39:23 +0800] "POST /portal.php?mod=portalcp&ac=diy HTTP/1.1" 500 186 "http://www.discuz.net/forum.php?diy=yes" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0" "-"

**Comment by ladygh** [comment]
补充一下关于上面的问题，error.log里有
        /usr/local/nginx/waf/waf.lua:66: in function </usr/local/etc/nginx/waf/waf.lua:1>, client: 60.225.48.223, server: www.discuz.net, request: "POST /portal.php?mod=portalcp&ac=diy HTTP/1.1", host: "www.discuz.net", referrer: "http://www.discuz.net/portal.php?diy=yes"

似乎是这个请求直接不能发送到后台，导致超时500错误。

**Comment by loveshell** [comment]
最后一条错误信息少了几行，能完整些吗。我稍后到家看下这个问题

**Comment by ladygh** [comment]
你说的最后一条错误信息是指哪个？我发的应该是完整的错误信息
我2楼3楼里说的问题通过白名单暂时解决了。似乎是2楼的这种post动作会直接引起执行错误

然后刚刚又发现几个问题
1. 文件上传检测似乎是大写拓展名的一概会被干掉。。。
2. 似乎post检测会检测所有的post内容，而不区分是在post的哪个位置。比如我想在post里发段代码 select * from ，会直接被干掉。

其他人也提到了这个问题，可以参考
http://www.leavesongs.com/OTHERLAN/diy-my-nginx-lua-waf.html

**Comment by ladygh** [comment]
又发现一个问题。。。对url的过滤。。。正则表达式写的不严谨。。
比如下面的图片因为文件名中有rar就会被干掉。。。
191829wwwz2rxxkkltrarw.jpg

**Comment by loveshell** [comment]
第一个问题，已经转义处理。
第二个问题，https://github.com/loveshell/ngx_lua_waf/blob/master/config.lua参考白名单配置
第三个问题，如果你在post里发一段sql，waf理所应当封杀。你可以通过白名单策略来调整
关于规则已经调整，具体业务规则还需要自行整理

**Comment by loveshell** [comment]
```
补充一下关于上面的问题，error.log里有
/usr/local/nginx/waf/waf.lua:66: in function , client: 60.225.48.223, server: www.discuz.net, request: "POST /portal.php?mod=portalcp&ac=diy HTTP/1.1", host: "www.discuz.net", referrer: "http://www.discuz.net/portal.php?diy=yes"

似乎是这个请求直接不能发送到后台，导致超时500错误。
```
这个问题，错误信息不足，无法解决。从提示分析应该是你的nginx配置文件client_max_body_size和client_body_buffer_size参数没设置好

**Comment by ladygh** [comment]
我个人觉得post的处理应该更智能化一些。
应该是针对不同的post类型来采取不同策略。
比如你在biog上想发一段关于sql的教程，按照目前的过滤必然会被当作攻击处理。

Ps:试着用了半天的was，似乎对性能影响有点大

Sent from my Windows Phone
________________________________

**Comment by loveshell** [comment]
关于post提交sql类操作，针对这个情况目前最好的办法就是定制白名单。
关于性能问题，由于这个版还有很大的优化空间。
ngx_lua_waf本身是个简单易懂的工具，主要给大家提供一个方法渠道。
抽空我把规则读取部分做下优化，放到内存里。

**Comment by ladygh** [comment]
白名单似乎是不支持query_string的白名单，只能设置对某文件(路径)的白名单吧。

Sent from my Windows Phone
________________________________

**Comment by loveshell** [comment]
是的,如果需要匹配query_string可以修改这里的ngx.var.uri为ngx.var.request_uri，为了以防不严格的编写造成问题，所以默认不采用那个接口处理
https://github.com/loveshell/ngx_lua_waf/blob/master/init.lua#L84

包括现在的waf规则读取主要为了大家好理解，所以没有变成lua文件存储。如果转换成lua文件的表方式存储规则，即可在启动时候加载到内存。性能将会大大提升
