### ISSUE TITLE
提几个需求建议。。

### ISSUE THREAD

**Issue by ladygh** [loveshell/ngx_lua_waf#41]
因为时差关系，昨天睡觉了。今天起来看昨天那个issue就被关掉了。。。
用了waf 一天多了，感觉还是有几个需要增强的地方

1. 对query_string做过滤。这个用途比较广
比如现在很多网站用nginx 来check refer来防盗链。我发现很多盗链的采用
http://*/jpg?0.190819083 这样类似的方式来破解盗链。
2. 可以针对query_string之类的做白名单
3.增加learning模式。比如开启后可以搜集网站上被访问过的php以及query_string，然后生成过滤规则。只要对不在规则内的php访问即deny
4.性能优化。。。。
5.上传文件误杀改进。。。

PS：乌云上这个貌似还没修正掉？
http://wooyun.org/bugs/wooyun-2010-0104525

**Comment by loveshell** [comment]
1.专业防盗链涉及双向策略，具体你需要根据个人情况定制，不在本项目范围
2.针对第二，第四和第五个问题，在之前的issue已经回复。
3.关于第三个问题，我暂时没时间去做。可以参考naxsi的白名单学习方法做。


如果你可以贡献patch最好不过了。

**Comment by loveshell** [comment]
ps部分问题不存在

**Comment by loveshell** [comment]
为了避免默认上传文件类型过多，引起误报。上传部分后缀名限制名单换成了黑名单限制，

**Comment by loveshell** [comment]
下载最新版本测试即可
