### ISSUE TITLE
更新nginx到1.8.0后waf不加载

### ISSUE THREAD

**Issue by ladygh** [loveshell/ngx_lua_waf#42]
版本如下
nginx-1.8.0
openresty-lua-nginx-module-v0.9.15-0

**Comment by loveshell** [comment]
什么提示呢

**Comment by ladygh** [comment]
没有任何提示，reload/restart nginx不会生成任何的waf的log
同时测试?id=../etc/passwd也没有任何效果
 
Date: Wed, 22 Apr 2015 20:53:35 -0700

**Comment by loveshell** [comment]
默认本机在ip白名单里。看看是不是这个地方影响测试了

**Comment by ladygh** [comment]
我最初怀疑是白名单的问题，已经把白名单清空了。依然是不加载
没有log。不知道log是在nginx启动时生成还是在检测到攻击后生成？

 
Date: Wed, 22 Apr 2015 21:14:34 -0700

**Comment by loveshell** [comment]
白名单清理了也没拦截？
日志目录需要有可写权限

**Comment by ladygh** [comment]
已经检查过了，目录权限没问题
唯一的变化就是升级了nginx版本。。
 
Date: Wed, 22 Apr 2015 21:21:57 -0700

**Comment by loveshell** [comment]
需要确认的是去掉ip白名单限制拦截了吗
日志方面目录给777看下

**Comment by ladygh** [comment]
确定不在白名单，确定目录有777
 

 
Date: Wed, 22 Apr 2015 21:25:40 -0700

**Comment by loveshell** [comment]
拦截了吗

**Comment by ladygh** [comment]
没有
waf不生效，连日志都没创建
 
我找另外一台机器配置一下WAF，然后升级nginx看看。
 
Date: Wed, 22 Apr 2015 21:28:47 -0700

**Comment by loveshell** [comment]
提供下各个路径和config的内容相关信息，可能是你的配置问题。没有足够的信息我也不好判定。兼容性应该不存在问题

**Comment by ladygh** [comment]
报告，刚刚把另外一台机器升级到ngxin1.8，一切正常。。
邪门了。难道是我昨天改nginx配置的原因
 
现在nginx是80端口监听，然后过滤请求，然后再发送到在unix socket listen的nginx。

 
Date: Wed, 22 Apr 2015 21:31:09 -0700

**Comment by ladygh** [comment]
找到问题了。
whiteurl这个文件里必须要写规则，我把默认规则干掉了，整个WAF就失效了
 
Date: Wed, 22 Apr 2015 21:31:09 -0700

**Comment by loveshell** [comment]
如果干掉规则应该不会出现这个情况的，你是不是留下了斜杠还是怎么操作的呢

**Comment by ladygh** [comment]
什么都没留，0大小的文件
 
Date: Wed, 22 Apr 2015 22:43:00 -0700

**Comment by loveshell** [comment]
我刚测试了没有重现你说的问题--！

**Comment by ladygh** [comment]
看了下我备份的文件
whitelist里是一个 回车  （\n ）,这种情况下就不生效
 
Date: Wed, 22 Apr 2015 22:55:32 -0700

**Comment by loveshell** [comment]
恩，不能有空行，稍后我修改下代码过滤空行

**Comment by ladygh** [comment]
另外一个关于client_body_buffer_size的问题，之前的issue里也反应过
似乎waf会显著增大post的client_body_buffer_size的大小？
设置client_body_buffer_size=8k
同样的内容，如果不加载waf，就可以正常post。但是加载waf之后，就会500错误，必须把client_body_buffer_size提高到16K。

**Comment by loveshell** [comment]
具体可参考https://github.com/loveshell/ngx_lua_waf/issues/26#issuecomment-55907523
