### ISSUE TITLE
能讲解一下那些规则是怎么定义的吗

### ISSUE THREAD

**Issue by baiys** [loveshell/ngx_lua_waf#44]
比如http://xxxx/test.php?id=../etc/passwd 为什么规则是这么写的(?:etc\/\W*passwd)

**Comment by loveshell** [comment]
pcre正则表达式

**Comment by baiys** [comment]
好的，谢谢 ！能留下联系方式或者有QQ群之类的吗，方便以后沟通交流

**Comment by loveshell** [comment]
微博私信吧
