### ISSUE TITLE
2015/05/14 10:49:52 [error] 7691#0: *439649845 lua entry thread aborted: runtime error: /usr/local/nginx/conf/waf/waf.lua:50: attempt to call field 'find' (a nil value)

### ISSUE THREAD

**Issue by CaesarC** [loveshell/ngx_lua_waf#48]
···
2015/05/14 10:49:52 [error] 7691#0: *439649845 lua entry thread aborted: runtime error: /usr/local/nginx/conf/waf/waf.lua:49: attempt to call field 'find' (a nil value)
···

不知道有沒有人遇到過

**Comment by loveshell** [comment]
ngx_lua低版本不支持ngx.re.find修改成ngx.re.match即可，我重新打个包，下载最新的就行

**Comment by CaesarC** [comment]
soga.感谢
