### ISSUE TITLE
lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/waf/waf.lua:47: attempt to index local 'm' (a number value)

### ISSUE THREAD

**Issue by lxdiyun** [loveshell/ngx_lua_waf#49]
上传的时候，报错
2015/06/03 08:59:10 [error] 3180#0: *8 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/waf/waf.lua:47: attempt to index local 'm' (a number value)
stack traceback:
coroutine 0:

**Comment by lxdiyun** [comment]
ngxmatch替换为ngx.re.find

**Comment by loveshell** [comment]
可以详细说明下吗，没明白到底什么情况

**Comment by lxdiyun** [comment]
就是在把ngxmatch替换为ngx.re.find的情况下，开启postmatch, 作文件上传，nnginx error log就会出报这个错误，提示的是
```log
2015/06/03 08:59:10 [error] 3180#0: *8 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/waf/waf.lua:47: attempt to index local 'm' (a number value)
stack traceback:
coroutine 0:
```
对应代码是：
```lua
...
local m = ngxmatch(data,'Content-Disposition: form-data;(.+)filename="(.+)\\.(.*)"','ijo')
if m then
          fileExtCheck(m[3])
          filetranslate = true
...
```

**Comment by loveshell** [comment]
后来代码调整，你同时修改下这个地方试试
https://github.com/loveshell/ngx_lua_waf/blob/master/waf.lua#L3

**Comment by lxdiyun** [comment]
也就是init和waf两个文件都改？

**Comment by loveshell** [comment]
下载最新版代码即可
