### ISSUE TITLE
是否有可以对指定的虚拟主机不启用waf

### ISSUE THREAD

**Issue by licess** [loveshell/ngx_lua_waf#50]
你好，是否有可以对指定的虚拟主机不启用waf

**Comment by loveshell** [comment]
参考历史说明：
https://github.com/loveshell/ngx_lua_waf/issues/2

**Comment by etangyushan** [comment]
etangyushan@126.com
 
发件人： loveshell
发送时间： 2015-06-11 23:48
收件人： loveshell/ngx_lua_waf
主题： Re: [ngx_lua_waf] 是否有可以对指定的虚拟主机不启用waf (#50)
参考历史说明：
#2

**Comment by etangyushan** [comment]
etangyushan@126.com
