### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by pysnow530** [loveshell/ngx_lua_waf#52]
为什么我的nginx加入waf支持后内存增长的厉害，把能off的都off了还是老样子，求指教

**Comment by loveshell** [comment]
规则文件读取问题，当初为了大家好理解，这个demo直接读取了文件内容。
修改lua规则为表的方式存储，放到lua文件里，开启lua_cache_code即可缓存起来。
稍后我调整下吧，确实有不少朋友反馈这个问题。
