### ISSUE TITLE
nginx报错

### ISSUE THREAD

**Issue by qinyz** [loveshell/ngx_lua_waf#53]
默认通过sh安装，虚拟机搭建的centos6.5 nginx转发流程到testphp.vulnweb.com，使用的是WVS扫描

不影响使用，就是想咨询一下，非常感谢
nginx错误日志
[error] 9137#0: *5980 lua entry thread aborted: runtime error: /usr/local/nginx/conf/waf/waf.lua:73: invalid value (boolean) at index 1 in table for 'concat'
stack traceback:
coroutine 0:
	[C]: in function 'concat'
	/usr/local/nginx/conf/waf/waf.lua:73: in function </usr/local/nginx/conf/waf/waf.lua:1>, client: 192.168.60.1, server: testphp.vulnweb.com, request: "POST //xmlrpc.php HTTP/1.1", host: "192.168.60.128
WAF的日志中记录
192.168.60.1 [2015-06-19 16:13:03] "POST testphp.vulnweb.com//xmlrpc" ""1.0"?>
 <!DOCTYPE foo [  
  <!ELEMENT methodName ANY >
  <!ENTITY xxe SYSTEM "file:///etc/passwd" >]>
<methodCall>
  <methodName>"  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36" "(?:etc\/\W*passwd)"

**Comment by loveshell** [comment]
https://github.com/loveshell/ngx_lua_waf/blob/master/waf.lua#L72
去掉后面的or val == false试试

**Comment by qinyz** [comment]
抱歉这么晚回复
更改后没有报错了，原因是什么呀

**Comment by loveshell** [comment]
容错没做好，已经修补
https://github.com/loveshell/ngx_lua_waf/commit/c0b121a64ced30e9e14818f7a9629077c56d8e6b
