### ISSUE TITLE
当post请求过大的时候，CPU飙升

### ISSUE THREAD

**Issue by amoa400** [loveshell/ngx_lua_waf#54]
当post请求过大，每次正则匹配的时间复杂度会非常高，导致CPU迅速飙升至100%，请问该如何解决

**Comment by loveshell** [comment]
这个看需求情况，如果不需要完全检测，分post数据类型，比如form-data的可以分流，只过滤每个数据流最前面多少字节数据。
所有市面的waf对于post的检测都没有很完美的处理方法。

**Comment by loveshell** [comment]
还有一个方案：根据情况，适当的时候选择DFA正则引擎做处理，比如google的re2或者春哥的sregex
