### ISSUE TITLE
postmatch开启后无法正常上传

### ISSUE THREAD

**Issue by yan1zhao** [loveshell/ngx_lua_waf#56]
首先感谢您开发的ngx_lua_waf插件。
我下载了最新的代码包，并按照流程装好了这个插件，能正常启动和拦截，我主要应用在discuz x2程序上。
但发现一个问题（可能是因为我不懂配置您这个插件），我只要将config.lua中的postmatch设为on，会员就无法上传论坛附件(登陆访问我们的网站均正常)，即使我把wafconf/post文件内容清空也是一样。目前只能将此项设为off，但这样防护效果肯定就打折扣了。
由于我不懂lua语法，因此想请问您是什么原因，感谢！

**Comment by loveshell** [comment]
hack.log里的拦截匹配规则你看看是哪个匹配的，删掉即可。

**Comment by yan1zhao** [comment]
您好，问题是拦截日志里，找不到上传附件被拦截的记录（其余的拦截行为均有记录）。但肯定是postmatch选项的原因，因为只要设置成on就无法上传，设置成off就立即正常。请指教，感谢！

**Comment by yan1zhao** [comment]
补充说明一下，我如果把某个IP设置为白名单，则这个IP的用户就可以正常上传了，无论此时postmatch是on还是off。另外附我的config：
RulePath = "/usr/local/openresty/nginx/waf/wafconf/"
attacklog = "on"
logdir = "/usr/local/openresty/nginx/logs/waflogs/"
UrlDeny="on"
Redirect="on"
CookieMatch="on"
postMatch="on" 
whiteModule="on" 
black_fileExt={"php","jsp"}
ipWhitelist={"223.151.252.169"}
ipBlocklist={"1.0.0.1"}
CCDeny="on"
CCrate="100/60"

**Comment by loveshell** [comment]
看起来是你提交的数据，被提取到的和预期不对应，麻烦微博私信我联系方式，远程协助看看

**Comment by yan1zhao** [comment]
请问您的微博是多少，方便的话直接加我的QQ434981576即可，有劳！

**Comment by yan1zhao** [comment]
请问您加我了吗，因为每天都有人加我，不知道哪位是您。麻烦您在QQ上联系我说明一下，感谢。

**Comment by yan1zhao** [comment]
您好，我已找到您的微博，并给您发了私信，感谢！
