### ISSUE TITLE
waf.ini another need fix part.

### ISSUE THREAD

**Issue by myiisvif** [loveshell/ngx_lua_waf#57]
tail /var/log/nginx/error.log
2015/07/28 16:19:12 [error] 3042#0: *19459 lua entry thread aborted: runtime error: /usr/local/nginx/conf/waf/waf.lua:73: invalid value (boolean) at index 1 in table for 'concat'
stack traceback:
coroutine 0:
        [C]: in function 'concat'
        /usr/local/nginx/conf/waf/waf.lua:73: in function </usr/local/nginx/conf/waf/waf.lua:1>, client: 172.16.16.162, server: xxxxx.com, request: "POST /xxxx.svc HTTP/1.1", host: "xxxxx.com"
2015/07/28 16:23:08 [error] 3041#0: *19966 lua entry thread aborted: runtime error: /usr/local/nginx/conf/waf/waf.lua:73: invalid value (boolean) at index 1 in table for 'concat'
stack traceback:
coroutine 0:
        [C]: in function 'concat'
        /usr/local/nginx/conf/waf/waf.lua:73: in function </usr/local/nginx/conf/waf/waf.lua:1>, client: 172.16.16.x, server: ywfw.qbjggzy.com, request: "POST /xxxxxx.svc HTTP/1.1", host: "xxxxx.com"

fix method just see this:

https://github.com/loveshell/ngx_lua_waf/commit/3b125676b13e294b79493f73afbb4c90a14ed40f

please fix it.

by softbug.

**Comment by loveshell** [comment]
v0.8.1 is fix it
