### ISSUE TITLE
500 Error "spdy not supported yet"

### ISSUE THREAD

**Issue by jmp0xf** [loveshell/ngx_lua_waf#58]
"2015/08/17 21:47:04 [error] 24755#0: *11 lua entry thread aborted: runtime error: **/**/waf/waf.lua:21: spdy not supported yet"
the exception raised by "ngx.req.socket()" and 500 was responded.

ngx_lua officially states spdy is not fully supported
http://wiki.nginx.org/HttpLuaModule#SPDY_Mode_Not_Fully_Supported

Could you please handle this exception?

**Comment by loveshell** [comment]
http://wiki.nginx.org/HttpLuaModule#SPDY_Mode_Not_Fully_Supported
ngx_lua limited
