### ISSUE TITLE
虚心请教下loveshell关于ngx_lua_waf配置文件如何配置比较妥当

### ISSUE THREAD

**Issue by janusdai** [loveshell/ngx_lua_waf#59]
HI loveshell：

首先非常感谢你分享该软件：

是这样的，最近我们网站遭到黑客注入攻击，所有站点目录都被植入恶意代码，甚至页面内容都换掉。
于是找到了这个软件，配置上去了，然后遇到些问题，恶意传参是拦截掉了，但是发现我们网站后台更新甚至用户发布产品也没法更新，也一起被拦截掉。

于是我又仔细看了说明文件，说明文件可能是老版本的，和现在新版下载下来文件，说明文件有点对不上，能否恳求作者能否把配置文件做详细说明教程一下，具体应该怎么配置比较妥当，怎么配置才能防止客户正常提交表单不会被屏蔽掉。
ps：我现在暂时凭感觉把UrlDeny和postMatch， off掉了，后台更新暂时没问题。

还有由于我刚从事运维不久，经验还不丰富，希望可以的话，能否留个联系方式，我想等你有空的时候，请教请教你。

**Comment by loveshell** [comment]
被屏蔽的地址，你填写到url白名单即可

**Comment by janusdai** [comment]
在whiteurl中一列列添加么
www.aaa.com
www.bbb.com
这样子添加么

还不太了解他是怎么过滤，更具什么过滤url的

**Comment by loveshell** [comment]
www.aaa.com/a/1.jsp
假设这个地址下的数据处理要放行，填写/a/1.jsp即可

**Comment by janusdai** [comment]
谢谢我明白了。还有个问题我发现开启防火墙后，lynx浏览器无法访问所有网页了，直接跳到拦截页面。lynx是一个文字版的浏览器。我们服务器上有很多定时任务，定时运行一些有统计功能的php应用文件，是然后用lynx 来执行的，请问这个该怎么设置呢

**Comment by virusdefender** [comment]
被攻击之后真心不建议用这个，规则有些简陋，只是适合自己开发和学习。

国内其他的云 waf 或者各种狗各种盾应该适合你。

**Comment by loveshell** [comment]
安全策略需要自行调整完善

**Comment by janusdai** [comment]
ok,谢谢各位
