### ISSUE TITLE
lua entry thread aborted: runtime error: /etc/nginx/waf/waf.lua:65: invalid value (boolean) at index 2 in table for 'concat'

### ISSUE THREAD

**Issue by xiagujinqiao** [loveshell/ngx_lua_waf#61]
嗨，你好。最近使用你的waf防火墙，发现几个问题，对于nginx body的解析，在某些特定的时候会失败。报错是：
2015/09/06 14:54:09 [error] 44749#0: *29170556087 lua entry thread aborted: runtime error: /etc/nginx/waf/waf.lua:65: invalid value (boolean) at index 2 in table for 'concat'
stack traceback:
coroutine 0:
        [C]: in function 'concat'
        /etc/nginx/waf/waf.lua:65: in function </etc/nginx/waf/waf.lua:1>, client: 10.10.10.11, server: api.app.com, request: "POST /common/sessionStart?appv=3.4.0&ch=AppStore_3.4.0.0&did=124726adsaa5dd89dc65e6db6&dt=iPhone7%2C2&im=1DDFE5D0-E1C2-4E51-BA28-5CBC31C04E5E&la=cn&latitude=37.774418&lm=weixin&longitude=75.216152&lp=-1.000000&net=0-0-wifi&osn=iOS&osv=8.3&seid=92eb54daa119c8a59c2a37a4&sh=568.000000&sw=320.000000&token=smUZkDlBzadas-HPJffRcjErmr_&tpid=home_follow&ts=1441522449108 HTTP/1.1", host: "api.abctest.com"

代码如下： 
57             for key, val in pairs(args) do
 58                 if val == nil then
 59                     return
 60                 end
 61                 if type(val) == "table" then
 62                     if type(val[1]) == "boolean" then
 63                         return
 64                     end
 65                     data=table.concat(val, ", ")
 66                 else
 67                     if val == false then
 68                         data=table.concat(val, ", ")
 69                     else
 70                         data=val
 71                     end
 72                 end
 73                 if data and type(data) ~= "boolean" and body(data) then
 74                     return true
 75                 end

你的原始代码是：
            for key, val in pairs(args) do
                if type(val) == "table" or val == false then
                    data=table.concat(val, ", ")
                else
                    data=val
                end
                if data and type(data) ~= "boolean" and body(data) then
                    return true
                end
因为之前，在不修改 if type(val[1]) == "boolean" then的时候，报错是lua entry thread aborted: runtime error: /etc/nginx/waf/waf.lua:59: invalid value (boolean) at index 1 in table for 'concat'，所以以为是对table的解析有问题，但是，实际对table的字段再次进行处理之后，发现，第二个值还是报这样的错误，所以怀疑是在特定的情况下，会对body解析出错，还请帮忙看下。。。
我用得并不是最新版。
谢谢！！！

**Comment by loveshell** [comment]
请问您那边能够重现该问题吗，麻烦提供相关数据和测试方法，我还跟进处理

**Comment by xiagujinqiao** [comment]
@loveshell 你好，不好复现，但是我现在线上还是在报错。
我修改代码之后，报警没有以前那么多，改之前，一天上千条这样的报错，改了之后，一天上百行左右，一天总请求量3亿左右。
之前，你的代码，是直接判断val是否为table类型，并处理。但是，实际情况，可能部分数据类型是table，但是，实际处理下来，concat并不成功。（只有极少数情况下出这个报错，同一个请求，我从日志里面抓出来用这个链接再次访问，可能就正常了）。

nginx的error日志如下：
2015/09/21 15:31:18 [error] 1029#0: *36548306605 lua entry thread aborted: runtime error: /etc/nginx/waf/waf.lua:65: invalid value (boolean) at index 2 in table for 'concat'
stack traceback:
coroutine 0:
    [C]: in function 'concat'
    /etc/nginx/waf/waf.lua:65: in function </etc/nginx/waf/waf.lua:1>, client: 10.10.10.12, server: api.app.com, request: "POST /common/sessionStart?appv=3.3.2&ch=AppStore_3.3.2.0&did=c747f120ed18b9f097af78edb&dt=iPhone7%2C2&im=CBAA47AF-F696-4B6E-98B0-78928AAF6&la=cn&latitude=22.728564&lm=mobile&longitude=114.244710&lp=-1.000000&net=null&osn=iOS&osv=8.1.3&seid=38bbe6efabcff7d7523e387c7&sh=667.000000&sw=375.000000&token=ME7uQV4ZIc2klVVupuYg&ts=1442820679208 HTTP/1.1", host: "api.app.com"

**Comment by loveshell** [comment]
参考
https://github.com/loveshell/ngx_lua_waf/commit/fa5bf74cbe2d3222efaf5c1b017073f1b37fa60e

**Comment by xiagujinqiao** [comment]
ok，谢谢，我线上也是这么解决的。
