### ISSUE TITLE
是否可以结合Iptables呢？

### ISSUE THREAD

**Issue by dovequn** [loveshell/ngx_lua_waf#62]
作者你好，请教你两个问题：

1、当攻击被抵御之后该IP地址将会被禁止访问的时间是多久？
2、每当抵御一次攻击，那么可以将此攻击的IP地址列入黑名单或者加入Iptables呢？或者可以执行一些脚本呢？

我从init.lua文件中看到当匹配一次攻击，那么就会有一个相应的防御动作，但是这个是用lua语言写的，我不会编程，所以想请教下如何改写这个防御动作呢？

问的有点多，还请作者见谅。谢谢。

**Comment by loveshell** [comment]
这个建议在iptables层面做，不要在ngx_lua层面做。
你可以尝试通过fail_ban来对hack.log里的攻击ip进行相关策略的处理

**Comment by dovequn** [comment]
谢谢作者你的回答，但是我还想问一下，当攻击被抵御之后该IP地址将会被禁止访问的时间是多久？因为我发现每次被抵御之后该IP地址在后续的5分钟左右就解锁了，那就意味着每隔五分钟就可以继续发起攻击，请问这个禁封的时间可以自己设置吗？谢谢。

**Comment by loveshell** [comment]
CCrate = "100/60"
    --设置cc攻击频率，单位为秒.
在config.lua配置里可以随意控制的

**Comment by dovequn** [comment]
CCrate选项是攻击频率啊，但是这并不是意味着可以将此IP禁封时间啊。谢谢作者了，我打算结合hack日志去实时添加IPtables规则，非常感谢。
