### ISSUE TITLE
报错 attempt to yield across C-call boundary 

### ISSUE THREAD

**Issue by idevz** [loveshell/ngx_lua_waf#65]
你好，ngx_lua_waf做的非常牛X，我把它继承到了我最近开发的一个框架里面[Vanilla](https://github.com/idevz/vanilla)，非常赞
，但是发现有个问题：
```
http://localhost:7200/?id=../etc/passwd#
```
如这个参数渗透，运行到```function args()```这个函数的时候报上面这个错，查了下是指到了```say_html```函数，```ngx.exit(ngx.status)```因为这个报错，是不是因为我集成的有问题？我将```ngx.exit(ngx.status)```替换成```ngx.eof()```暂时解决了这个问题。
如下图：

<img width="871" alt="2015-09-26 11 17 41" src="https://cloud.githubusercontent.com/assets/2113827/10118259/b17bc002-64a6-11e5-830c-fce9dfef59be.png">

**Comment by loveshell** [comment]
从作用范围
```
ngx.eof
	rewrite_by_lua*, access_by_lua*, content_by_lua*
ngx.exit¶
	rewrite_by_lua*, access_by_lua*, content_by_lua*, header_filter_by_lua*, ngx.timer.*
```
这个可能跟您的框架套用这个程序的阶段有关系。
