### ISSUE TITLE
修复：/ngx_lua_waf/waf.lua:75: invalid value (boolean) at index 1 in table for 'concat'

### ISSUE THREAD

**Issue by zheng-ji** [loveshell/ngx_lua_waf#69]
Dear Loveshell:

It is a nice program,and we benefit a lot from it.Thank you for sharing :)
but i got  a problem like that:
```
/ngx_lua_waf/waf.lua:75: invalid value (boolean) at index 1 in table for 'concat'
```

And i solved that by modifying `waf.lua`  with the following codes begin at Line73

```
 if type(val[1]) == "boolean" then
     return
 end
```

**Comment by loveshell** [comment]
thx for your patch
