### ISSUE TITLE
关于POST上传照片是容易误报的问题反馈

### ISSUE THREAD

**Issue by ysyx2008** [loveshell/ngx_lua_waf#74]
POST上传照片时很容易被拦截，其他参数均正常，怀疑是图片编码被错误匹配了。

对应的拦截规则是这一行：
\<(iframe|script|body|img|layer|div|meta|style|base|object|input)

但UTF-8打开日志文件后，找不到对应的字符。不知道有没有解决办法？

**Comment by loveshell** [comment]
可以删掉这条规则，或者完善下这条规则都可以的

**Comment by jiespring** [comment]
删掉post文件里的这条规则也没用

**Comment by jiespring** [comment]
最简单就是post_match 'off'
