### ISSUE TITLE
关于一个url规则写法的疑问

### ISSUE THREAD

**Issue by ysyx2008** [loveshell/ngx_lua_waf#85]
`http://abc.def.com.cn:8080/image.jsp?url=*/-->'");></iframe></script></style></title><a href='http://www.baidu.com'>link injecting</a> 
`

这样的URL存在注入漏洞，但在配置文件url中写“iframe>”规则无法匹配，而“iframe”可以，这是什么原因呢？正则匹配的问题吗？

**Comment by loveshell** [comment]
这个策略应该写到args文件里。或者修改
https://github.com/loveshell/ngx_lua_waf/blob/master/init.lua#L81
这行的ngx.var.uri为ngx.var.request_uri即可
