### ISSUE TITLE
post绕过问题

### ISSUE THREAD

**Issue by bajief** [loveshell/ngx_lua_waf#89]
post时，如果body内容不是标准的，或没有=，将被绕过，比如postbody内容为：

<?php
echo system($_POST['abcd']);
?>

这个php提交是会绕过，上传成功，解决办法是把修改第80行：
if data and type(data) ~= "boolean" and body(data) then
else body(key)

**Comment by loveshell** [comment]
thx !
https://github.com/loveshell/ngx_lua_waf/commit/314a2f62ec350eba9b5d25b55b5b0a723e20a8d0
