### ISSUE TITLE
和nginx_upload_module冲突

### ISSUE THREAD

**Issue by snail007** [loveshell/ngx_lua_waf#95]
如果启用了防火墙，在nginx.conf里面加上如下防火墙配置
init_by_lua_file  /server/tengine/conf/ngx_lua/waf/init.lua;
access_by_lua_file /server/tengine/conf/ngx_lua/waf/waf.lua;
，就会导致上传模块：https://github.com/vkholodkov/nginx-upload-module  无法工作，返回500.
注释掉上面两行，上传模块就可以工作正常。

**Comment by weakestan** [comment]
增加路径白名单，跳过上传地址检测就行了。
针对文件上传，fileExtCheck(m[3])这里好像不够完善。水平不够还改不来。
